# This rule runs medaka to polish the assembly generated by flye using the trimmed reads     
rule medaka:
    input:
        trimmed = "results/{prefix}/filtlong/{barcode}/{barcode}.trimmed.fastq.gz",
        flye_assembly = "results/{prefix}/flye/{barcode}/{barcode}_flye_circ.fasta",
    output:
        medaka_out = "results/{prefix}/medaka/{barcode}/{barcode}_medaka.fasta", # Note: medaka_out is the final assembly with circularization info
        medaka_out_wo_circ = "results/{prefix}/medaka/{barcode}/{barcode}_medaka_wo_circ.fasta", # Note: medaka_out_wo_circ is used to generate the medaka assembly without circularization
    params:
        medaka_out_dir = "results/{prefix}/medaka/{barcode}",
        medaka_out_dir_wo_circ = "results/{prefix}/medaka/{barcode}/wo_circ",
        threads = config["threads"],
        prefix = f"{{barcode}}",
    #log:
    #    "logs/{prefix}/medaka/{barcode}/{barcode}.log"
    singularity:
        "docker://staphb/medaka:1.2.0" # Keep older version of medaka since model used is not supported in the latest version i.e. medaka v2.0.1, 2025-04-29
    #envmodules:
    #    "Bioinformatics",
    #    "medaka",
    #    "bcftools"
    shell:
        """
        medaka_consensus -i {input.trimmed} -d {input.flye_assembly} -o {params.medaka_out_dir} -t {params.threads} -m r941_min_high_g303 &&
        cp {params.medaka_out_dir}/consensus.fasta {params.medaka_out_dir}/{params.prefix}_medaka.fasta 
        
        cp {params.medaka_out_dir}/{params.prefix}_medaka.fasta  {output.medaka_out_wo_circ} 
        sed -i 's/;.*//' {output.medaka_out_wo_circ}
        
        """ 
